### ISSUE TITLE
Off by one for sub-resources

### ISSUE THREAD

**Issue by arueth** [QualiSystems/Juniper-JunOS-Shell#32]
With the 3.0.0 release, it looks like the numbers for the sub-resources starts with 1 instead of 0. This causes the names to not match up:

Chassis 1
--> Module 1
---->Submodule 1
------> xe-0-0-0

should be:

Chassis 0 or 1 (This one is not as important)
--> Module 0
----> Submodule 0
------> xe-0-0-0 (interface-module-submodule-port)

I'm not sure if this is a new or existing issue.

**Comment by GalcQuali** [comment]
We will investigate this issue.

**Comment by GalcQuali** [comment]
This issue is resolved in latest JunOS release.
