### ISSUE TITLE
Populating the address attribute of ports with the CLI port name

### ISSUE THREAD

**Issue by arueth** [QualiSystems/Juniper-JunOS-Shell#33]
For the address attribute of ports, would it be possible to populate that tribute with the CLI port name representation?

Name: xe-0-0-0
Address xe-0/0/0

This would save having to do - to / conversations.

**Comment by GalcQuali** [comment]
Due to limitations in CloudShell we can not use "/" at the address of a resource.

**Comment by arueth** [comment]
What is the limitation in using "/" in the address attribute? I'm able to enter an addresses with a "/" today.

**Comment by GalcQuali** [comment]
The full address of a resource is combining the parent resources addresses with “/” separated. If you have it in the specific resource address it messes up the full address and create issues on the server when trying to run commands on this resource.

Gal Cohen  |  R&D Shells Manager
Office: +972-77-9014000 ext. 108
Mobile: +972-54-2552015
Web: www.quali.com<http://www.quali.com/>
[cid:image001.jpg@01D1D515.346663D0]
